package controllers.line;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextInputDialog;
import javafx.scene.layout.BorderPane;
import javafx.stage.Modality;
import javafx.stage.Stage;
import managers.LineMapSelectorManager;
import models.BusLineRoute;
import models.BusStop;
import models.Route;
import models.busline.BusLine;
import src.com.brunomnsilva.smartgraph.graphview.SmartGraphEdge;

public class LineRouteSelectorController implements Initializable{
	@FXML
	private BorderPane borderPane;
	@FXML
	private Button cancelButton;
	@FXML
	private Button saveButton;
	
	private LineMapSelectorManager selectorManager;
	
	public void init(BusLine busLine) {
		selectorManager.setBusline(busLine);
		selectorManager.initView();
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		selectorManager = new LineMapSelectorManager();
		borderPane.setCenter(selectorManager.getMapView());
		selectorManager.setEdgeDoubleClickAction((SmartGraphEdge<Route,BusStop> ed) ->{
			try {
				FXMLLoader loader = new FXMLLoader(getClass().getResource("/views/line/EstimatedTimeRoute.fxml"));
				Parent root = loader.load();
				EstimatedTimeRouteController controller = loader.getController();
				controller.setBusLineRoute(new BusLineRoute(selectorManager.getBusLine(),ed.getUnderlyingEdge().element()));
				Scene scene = new Scene(root);
				Stage stage = new Stage();
				stage.initModality(Modality.APPLICATION_MODAL);
				stage.setScene(scene);
				stage.showAndWait();
				if(controller.isNewRoute()) {
					selectorManager.addRouteMap(controller.getBusLineRoute());
				}
			} catch (IOException e) {
				e.printStackTrace();
			}
			
			
		});
	}
	
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancel(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#saveButton].onAction
	@FXML
	public void save(ActionEvent event) {
		// TODO Autogenerated
	}

}
